from ibge import *

ibge = Regioes()
print(ibge.count())
print(ibge.json())
print(ibge.getId())
print(ibge.getSigla())
print(ibge.getNome())

ibge = Estados()
print(ibge.count())
print(ibge.json())
print(ibge.getId())
print(ibge.getSigla())
print(ibge.getNome())

ibge = Municipios()
print(ibge.count())
print(ibge.json())
print(ibge.getNome())
print(ibge.getId())
print(ibge.getDescricaoUF())
print(ibge.getDados())

ibge = Municipio('3303609')
print(ibge.count())
print(ibge.json())
print(ibge.getNome())
print(ibge.getId())
print(ibge.getUF())
print(ibge.getDescricaoUF())

ibge = MunicipioPorUF('51')
print(ibge.count())
print(ibge.json())
print(ibge.getId())
print(ibge.getNome())
